---
apiVersion: v1
kind: configMap
metadata: 
  name: my-configmap-nginx
data:
  default.conf: |
    server {
      listen 80 default_server;
      server_name _;
      
      default_type text/plain;
      
      lacation / {
        return 200 '$hostname\n';
      }
    }
...
